project_id = "hvmrjymweajxxkoiupzf"

[functions.slack-auth]
verify_jwt = true

[functions.slack-callback]
verify_jwt = false

[functions.slack-members]
verify_jwt = false

[functions.slack-channels]
verify_jwt = false

[functions.slack-join-channel]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
